feat: allow async onExecuteDone hook
dotansimha/envelop pull request #869
Opened 2021-10-24 15:29 UTC by EmrysMyrddin

## Description

Allow async function for the onExecuteDoneHook.

One exemple of use case is to allow wraping every execution into a database transaction with automatic commit/rollback as shown in the linked issue.

Fixes #868

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Screenshots/Sandbox (if appropriate/relevant):

Example of plugin using this feature :

```ts
export function useTransactions(options): TransactionsPlugin {
  return {
    async onExecute({ args: { contextValue } }) {
      const operationType = getOperationType(contextValue)
      if(operationType != 'query' && operationType != 'mutation') return
      
	  const transaction = await options.newTransaction(operationType === 'query' ? 'read-only' : 'auto')
      
      return {
        async onExecuteDone({result}) {
          try {
          	if(isAsyncIterable(result)) throw TypeError('Async Iterable results are not implemented')
            if(result.errors) throw result.errors
            await transaction.commit()
          } catch (err) {
            await transaction.rollback(err)
          } finally {
            await transaction.releaseClient()
          }
        }
      }
    }
  }
}
```

## How Has This Been Tested?

- [x] Unit test which tests that it is possible to return a Promise from an OnExexcuteDoneHook

**Test Environment**:

- OS: macOs
- `@envelop/core`: 1.3.0
- NodeJS: v16.11.1

## Checklist:

- [x] I have followed the [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-10-24 15:59 UTC, n1ru4l requested changes
Looks legit to me 🙏 Thank you! Would you mind adding a changeset?

2021-10-24 16:02 UTC, EmrysMyrddin commented
Sure, is it a minor or a patch ?

2021-10-24 16:03 UTC, n1ru4l commented
@EmrysMyrddin patch is for bug fixes, as this is a new feature this is a minor :)

2021-10-24 16:06 UTC, EmrysMyrddin commented
Done 👌

2021-10-25 08:52 UTC, dotansimha commented
Thanks @EmrysMyrddin ! This is awesome!!!

2021-10-25 08:53 UTC, dotansimha commented
Btw, I think `useTransactions` is an interesting approach. Maybe we can add a guide/example in the website for tackling this kind of thing with Envelop? :)

2021-10-25 08:53 UTC, merged

2021-10-25 09:15 UTC, EmrysMyrddin commented
It could be a good idea yes, but keep in mind that the code shown is a very simplified version.

We probably want a plugin that is handling this properly with a generic way :)

We are working on plugin that is handling databases interactions (with many other things ^^), perhaps we could extract a reusable and shareable plugin out of our codebase.