feat: allow enableIf to accept a funciton
dotansimha/envelop pull request #888
Opened 2021-10-26 03:33 UTC by saihaj

Closes #875

2021-10-26 03:33 UTC, saihaj commented
@dotansimha I am not sure how to test if a plugin's init is called or not : )?

2021-10-26 06:37 UTC, dotansimha requested changes

2021-10-26 06:37 UTC, dotansimha commented on packages/core/src/enable-if.ts
> +    return plugin instanceof Function ? plugin() : plugin;
Please replace `instanceof Function` with `typeof`, it should be faster :)

2021-10-26 06:37 UTC, dotansimha commented
> @dotansimha I am not sure how to test if a plugin's init is called or not : )?

You can create a "fake plugin" that is only a `jest.fn().mockImplementation(() => ({})` and check if it was called.

2021-10-27 14:30 UTC, dotansimha commented
@saihaj i guess it needs a rebase?

2021-10-27 15:22 UTC, saihaj commented
> @saihaj i guess it needs a rebase?

The failing ci is related to https://github.com/graphql/graphql-js/issues/3340

2021-10-27 15:50 UTC, saihaj commented
@dotansimha should be good now

2021-10-27 17:20 UTC, merged